" Welcome to your .vimrc!

set nocompatible

" Make Vim conform to the XDG Home Directory Standard
set undodir=$XDG_DATA_HOME/vim/undo
set directory=$XDG_DATA_HOME/vim/swap
set backupdir=$XDG_DATA_HOME/vim/backup
set viewdir=$XDG_DATA_HOME/vim/view
set viminfo+='1000,n$XDG_DATA_HOME/vim/viminfo
set runtimepath=$XDG_CONFIG_HOME/vim,$VIMRUNTIME,$XDG_CONFIG_HOME/vim/after

" The following line turns syntax highlighting on by default.
syntax on

" This section is for installing vim plugins.
" See https://github.com/junegunn/vim-plug for more information.
call plug#begin('~/.config/vim/plugged-ins')

Plug 'reedes/vim-pencil'
Plug 'tpope/vim-commentary'
Plug 'christoomey/vim-system-copy'
Plug 'mattn/vim-starwars'
" Plug 'lervag/vimtex'

call plug#end()

" This section configures the Pencil plugin.
" See https://github.com/reedes/vim-pencil for more information.
filetype plugin on

" Set the default wrap mode to soft, as in MS Word.
let g:pencil#wrapModeDefault = 'soft' 

"Turn on the Pencil plugin for certain files
augroup pencil
	autocmd!
	autocmd FileType markdown,mkd 	call pencil#init()
	autocmd FileType text		call pencil#init()
augroup END

" Turn on line numbers
set number

" Allow backspace over specified text objects
set backspace=indent,eol,start 

" Runs command-line command "setlocal spell spelllang=en_us"
" for all text files i.e. turns on vim's built-in spellcheck.
autocmd FileType text setlocal spell spelllang=en_us,fr

" Add French to spell-checked languages
" set spelllang+=fr

" Set tabs to four spaces
filetype plugin indent on
" show existing tab with 4 spaces width
set tabstop=4
" when indenting with '>', use 4 spaces width
set shiftwidth=4
" On pressing tab, insert 4 spaces
set expandtab

" let g:tex_flavor = 'latex'
